spring:
  application:
    name: cas-project
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/casproject}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework.security: INFO

server:
  address: 0.0.0.0
  port: 8080

app:
  frontend-url: https://casproject.santoriello.ch

jwt:
  secret: ${JWT_SECRET:}
